session_name: space
start_directory: "/home/duclos/Documents/uni/space/microsemi-error-detection/"
windows:
  - window_name: md
    panes:
      - nvim README.md
  - window_name: bash
    layout: even-horizontal
    panes:
      - clear && ls -l
      - nvim Makefile
  - window_name: src
    start_directory: "/home/duclos/Documents/uni/space/microsemi-error-detection/microsemi/"
    panes:
      - nvim .
  - window_name: py
    panes:
      - nvim main.py
