session_name: space
start_directory: "/home/duclos/Documents/topics/hw/microsemi-error-detection/"
windows:
  - window_name: md
    panes:
      - nvim README.md
  - window_name: bash
    layout: even-horizontal
    panes:
      - clear && ls -l
      - nvim Makefile
  - window_name: src
    panes:
      - nvim .
  - window_name: py
    panes:
      - nvim main.py
  - window_name: wiki
    panes:
      - ls -l
